/*
 * Defines the comparison operators. We could also get away with
 * only 3 and use negation...
 *
 *
 */
public class fflib_ComparisonOperator {
	public static final String  EQUAL =' = ',
	NOT_EQUAL= ' != ',
	LESS_THAN = ' < ',
	LESS_THAN_OR_EQUAL =' <= ',
	GREATER_THAN = ' > ',
	GREATER_THAN_OR_EQUAL=' >= ',
	IS_IN = ' IN ';

//	public abstract ComparisonOperator negated();
//
//	public abstract ComparisonOperator invert();
//
//	public abstract ComparisonOperator broader();
//
//	public abstract ComparisonOperator sharper();

	//public abstract String sqlText();
}
