/**
 * File Name: sflib_Operator 
 * Description: Enum of Operators
 * Copyright (c) 2018 Johnson & Johnson
 */
public enum fflib_Operator
{
	EQUALS,                   // =
	NOT_EQUALS,               // !=
	LESS_THAN,                // <
	LESS_THAN_OR_EQUAL_TO,    // <=
	GREATER_THAN,             // >
	GREATER_THAN_OR_EQUAL_TO, // >=
	LIKEx,                    // like

	INCLUDES,                 // includes
	EXCLUDES,                 // excludes
	INx,                      // in
	NOT_IN,                   // not in
	ANDx,                     // AND
	ORx                       // OR
}