name: Manage SF API Versions
on:
  workflow_dispatch:
    inputs:
      api-version:
        description: 'api version in the format XX e.g 58'
        required: true
        type: string
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: apex-enterprise-patterns/manage-sf-api-version@v1.0.0
        with:
          api-version: ${{inputs.api-version}}
      - uses: peter-evans/create-pull-request@v5
        with:
          title: 'Bump API Versions to ${{inputs.api-version}}.0'
          body: 'Automatically bumped by GitHub Actions '
          branch: 'devops/bump-api-versions-v${{inputs.api-version}}.0'
          commit-message: 'chore: bump api to v${{inputs.api-version}}.0'
